---
##kernel parameters
kernel_parameters:
  - { param: 'net.core.somaxconn', value: '1024' }
  - { param: 'net.core.netdev_max_backlog', value: '5000' }
  - { param: 'net.core.rmem_max', value: '16777216' }
  - { param: 'net.core.wmem_max', value: '16777216' }
  - { param: 'net.ipv4.tcp_wmem', value: '4096 12582912 16777216'}
  - { param: 'net.ipv4.tcp_rmem', value: '4096 12582912 16777216'}
  - { param: 'net.ipv4.tcp_max_syn_backlog', value: '8096' }
  - { param: 'net.ipv4.tcp_slow_start_after_idle', value: '0' }
  - { param: 'net.ipv4.tcp_tw_reuse', value: '1' }
  - { param: 'net.ipv4.ip_local_port_range', value: '10240 65535'}
  - { param: 'net.ipv4.tcp_timestamps', value: '0' }
  - { param: 'vm.swappiness', value: '10' }

##create user
user_name: test8
user_password: Test1!
user_group: test8

##change hostname
host_name: test-web01

##Apache and Nginx
serveradmin: test@example.com
domain_name: test.com

##MySQL
root_password: Testtest991!

##MySQL Log
logs_dbpass: Mysqllog991!
rotate_num_mysql: 60

##dokcer-compose URL
docker_compose_url: https://github.com/docker/compose/releases/download/1.24.1/docker-compose-Linux-x86_64

##php remi URL
php_remi_url: https://rpms.remirepo.net/enterprise/remi-release-9.rpm

##php version
php_version: 80

##php modules
php_modules:
  - "php"
  - "php-cli"
  - "php-devel"
  - "php-common"
  - "php-json"
  - "php-xml"
  - "php-mbstring"
  - "php-pdo"
  - "php-gd"
  - "php-process"
  - "php-intl"
  - "php-fpm"
  - "php-zip"
  - "php-bcmath"

##zabbix repository URL
zabbix_repository_url: https://repo.zabbix.com/zabbix/5.0/rhel/9/x86_64/zabbix-release-5.0-3.el9.noarch.rpm

##zabbix server IP
zabbix_server_ip: 192.168.33.80

##zabbix mysql pass
zabbix_dbpass: Zabbixmysql991!