---
- name: remove mariadb
  yum:
    name: mariadb-libs
    state: absent

- name: remove default mysql-community
  yum:
    name: mysql-community-*
    state: absent

- name: install RPM-GPG-KEY-mysql
  rpm_key:
    key: https://repo.mysql.com/RPM-GPG-KEY-mysql-2022
    state: present

- name: install repository for mysql
  shell: dnf localinstall https://dev.mysql.com/get/mysql80-community-release-el9-5.noarch.rpm -y

#- name: disable mysql:8.0
#  shell: dnf module disable mysql -y

- name: install optional packages
  yum:
    name: 
      - python-PyMySQL
      - expect
    state: present

- name: install mysql community devel
  yum:
    name: mysql-community-devel*
    state: present

- name: install mysql community server
  yum:
    name: mysql-community-server*
    state: present

- name: start mysqld
  service:
    name: mysqld
    state: started
    enabled: yes

- name: copy my.cnf
  copy:
    src: ../templates/my.cnf
    dest: /etc
  notify:
    - restart mysqld

- name: mkdir log directory
  file:
    path: /var/log/mysql
    state: directory
    recurse: yes
    owner: mysql
    group: mysql

- name: create a directory for file descriptor
  file:
    path: /etc/systemd/system/mysqld.service.d
    state: directory
    mode: "0755"
    recurse: yes

- name: copy limits.conf
  template:
    src: ../templates/limits.conf
    dest: /etc/systemd/system/mysqld.service.d/limits.conf

- name: modify log output
  command: sed -i -e "s/^log-error = \/var\/log\/mysqld.log/log-error = \/var\/log\/mysql\/mysqld.log/g" /etc/my.cnf
  command: sed -i -e "s/^#slow_query_log = 1/slow_query_log = 1/g" /etc/my.cnf
  command: sed -i -e "s/^#slow_query_log_file = \/var\/log\/mysql\/slow.log/slow_query_log_file = \/var\/log\/mysql\/slow.log/g" /etc/my.cnf
  command: sed -i -e "s/^#long_query_time = 1/long_query_time = 1/g" /etc/my.cnf
  notify:
    - restart mysqld

- name: get root password
  shell: "grep 'A temporary password is generated for root@localhost' /var/log/mysqld.log | awk -F ' ' '{print $(NF)}'"
  register: org_root_password

- name: update root user plugin
  command: mysql --user root --password={{ org_root_password.stdout }} --connect-expired-password --execute="ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{ root_password }}';"

- name: create mysql user
  mysql_user:
    login_user: root
    login_password: "{{ root_password }}"
    name: "{{ db_user_name }}"
    password: "{{ db_user_password }}"
    priv: "*.*:ALL"
    host: localhost
    state: present

- name: create mysql database
  mysql_db:
    login_user: root
    login_password: "{{ root_password }}"
    name: "{{ db_name }}"
    state: present

- name: put mysql_config_editor
  template:
    src: ../templates/mysql_config_editor
    dest: /tmp
    owner: root
    group: root
    mode: 0755

- name: exec mysql_config_editor
  shell: "/tmp/mysql_config_editor"
